name: Docker Image CI

on:
  push:
    branches: [ master, minisatip_1.3 ]
  pull_request:
    branches: [ master, minisatip_1.3 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and Push (latest)
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: catalinii/minisatip-build-image:minisatip_1.3
          secrets: |
            "TOKEN2=${{ secrets.COVERITY_SCAN_TOKEN }}"

#        TOKEN2: ${{ secrets.COVERITY_SCAN_TOKEN }}

